config/routes.rb
Rails.application.routes.draw do
  resources :words, only: [:new, :create]
  devise_for :users
  root 'static_page#home'
  get 'dashboard', to: 'static_page#dashboard'
  get 'write', to: 'words#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :uid

  has_many :words
  validates_presence_of :name
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :user
  validates_presence_of :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  before_action :authenticate_user!, only: [:dashboard]
  def home
    if user_signed_in?
      redirect_to :dashboard
    end
  end

  def dashboard
    unless current_user.confirmed?
      redirect_to :home, notice: "Your email is not confirmed. Please confirm using the link sent to your email."
    end
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]



  # GET /words/new
  def new
    @user = User.find_by_uid params[:user]
    if @user
      @word = Word.new
      @word.user = @user
    else
      render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found
    end

  end



  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        WordMailer.with(word: @word).word_mail.deliver_later
        format.html { redirect_to new_user_registration_path,
                                  notice: 'You have successfully said your words. Why not get your own account?' }
      else
        format.html { render :new }

      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:user_id, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book Of Secret Words</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "partials/notify" %>
    <%= yield %>
  </body>
</html>

app/views/partials/_notify.html.haml
- if !notice.blank?
  :javascript
      $(document).ready(function () {
        $.notify({
          message:  "#{notice}"
        });
      });
- if !alert.blank?
  :javascript
      $(document).ready(function () {
        $.notify({
          message:  "#{alert}"
        });
      });

app/views/partials/_word.html.haml
%div
  %span
    %strong
      Anonymous
    says on
    %strong
      = word.created_at.localtime

  %hr
  %p.word-p
    = word.body

app/views/static_page/dashboard.html.haml
%nav.navbar.navbar-dark.bg-dark
  %span.navbar-brand.mb-0.h1 Book Of Secret Words
  = link_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-danger"
.container#share
  %h2 Share your URL:
  %span#url= "#{root_url}write?user=#{current_user.uid}"
  %button.btn.btn-primary#urlbtn Copy
.container
  %h2 Here's what the world has to say about you -
  - if current_user.words.empty?
    .container
      %span Oops, looks like nobody has said anything yet. Have you shared your URL?
  -current_user.words.each do |word|
    %p
      = render partial: "partials/word", locals: { word: word }

app/views/static_page/home.html.haml
%header
  .jumbotron.jumbotron-fluid
    .container
      %h1.display-4 Book of Secret Words
      %p.lead Get anonymous feedback from people around you
      %hr.my-4
      =link_to "Register", new_user_registration_path, class: "btn btn-primary btn-lg"
      =link_to "Log in", new_user_session_path, class: "btn btn-lg"

app/views/words/_form.html.erb
<header>

  <div class="container" id="reg-box">
    <h1>Say something about <%= @word.user.name %></h1>
    <%= form_with(model: word, local: true) do |form| %>
      <% if word.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(word.errors.count, "error") %> prohibited this word from being saved:</h2>

          <ul>
            <% word.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.text_field :user_id, hidden: true %>
      </div>
      <div class="field form-group">
        <%= form.text_area :body, placeholder: "Say your mind", class: "form-control" %>
      </div>

      <div class="actions">
        <%= form.submit "Say", class: "btn btn-primary mb-2" %>
      </div>
    <% end %>
  </div>
</header>

app/views/words/edit.html.erb
<h1>Editing Word</h1>

<%= render 'form', word: @word %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Words</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= word.user %></td>
        <td><%= word.body %></td>
        <td><%= link_to 'Show', word %></td>
        <td><%= link_to 'Edit', edit_word_path(word) %></td>
        <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Word', new_word_path %>

app/views/words/new.html.erb
<%= render 'form', word: @word %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @word.user %>
</p>

<p>
  <strong>Body:</strong>
  <%= @word.body %>
</p>

<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>